import { join } from "node:path"
import type { ExtractionRule } from "./model.ts"

// ─── Default vocabulary (REQ-{NNNN}-{NNN}, REQ-{NNNN}-{NNN}, DEC-{N} decision 3) ───────

/**
 * Standard core default indexed_paths: 3 only.
 * Self-hosting-specific paths (src/opencode, .opencode, .agentdev/extensions,
 * scripts, tests) are NOT included — they belong in self-hosting augmentation
 * (Issue #1951 scope, REQ-{NNNN}-{NNN}).
 */
export const DEFAULT_INDEXED_PATHS = [
  "docs/requirements",
  "docs/decisions",
  "docs/specs",
] as const

/**
 * Standard core default node_types vocabulary: 3 only.
 * command, skill, integrity_rule, extension, source_file are added by
 * augmentation (REQ-{NNNN}-{NNN}).
 */
export const DEFAULT_NODE_TYPE_VOCABULARY = [
  "requirement",
  "decision",
  "specification",
] as const

/**
 * Standard core default relation_types vocabulary: 5.
 * delegates_to, governs are added by augmentation (DEC-{N} decision 3).
 */
export const DEFAULT_RELATION_TYPE_VOCABULARY = [
  "references",
  "supersedes",
  "defined_in",
  "contains",
  "extends",
] as const

// ─── Excluded paths (same semantics as repo-local) ────────────────────────────

export const EXCLUDED_PATHS = [
  ".agentdev/graph/**",
  ".agentdev/artifact-graph.yaml",
  ".git/**",
  ".worktrees/**",
  "node_modules/**",
  "dist/**",
  "outputs/**",
  ".cache/**",
  ".omo/**",
  ".sisyphus/**",
  "**/*.tmp",
] as const

const EXCLUDED_SEGMENTS = new Set([
  ".git", ".worktrees", "node_modules", "dist", "outputs", ".cache", ".omo", ".sisyphus",
])

const INPUT_EXTENSIONS = new Set([
  ".md", ".yaml", ".yml", ".ts", ".tsx", ".mts", ".cts", ".json", ".jsonc", ".ps1", ".sh",
])

export function isExcludedPath(path: string): boolean {
  const parts = path.split("/")
  if (parts.some((part) => EXCLUDED_SEGMENTS.has(part))) return true
  if (path === ".agentdev/graph" || path.startsWith(".agentdev/graph/")) return true
  if (path === ".agentdev/artifact-graph.yaml") return true
  return path.endsWith(".tmp")
}

export function isInputFile(path: string): boolean {
  const dot = path.lastIndexOf(".")
  return dot >= 0 && INPUT_EXTENSIONS.has(path.slice(dot).toLowerCase())
}

// ─── Open extension point: rules and config (REQ-{NNNN}-{NNN}, DEC-{N} decision 2) ─

export type LabelSourceStep =
  | { readonly kind: "frontmatter_field"; readonly field: string }
  | { readonly kind: "first_heading" }
  | { readonly kind: "filename_stem" }
  | { readonly kind: "path_group"; readonly group: number }
  | { readonly kind: "literal"; readonly value: string }
  | { readonly kind: "path" }

export type NodeTypeRule = {
  readonly name: string
  readonly path_pattern: string
  readonly id_template: string
  readonly label_source: readonly LabelSourceStep[]
  readonly extraction_rule: ExtractionRule
}

export type RelationTypeRule = {
  readonly name: string
  readonly fields: readonly string[]
  readonly reverse_direction: boolean
}

export type ResolvedConfig = {
  readonly node_type_rules: readonly NodeTypeRule[]
  readonly node_type_vocabulary: readonly string[]
  readonly relation_type_rules: readonly RelationTypeRule[]
  readonly relation_type_vocabulary: readonly string[]
  readonly indexed_paths: readonly string[]
  readonly discovery_roots: readonly string[]
  readonly excluded_paths: readonly string[]
}

// ─── Default rules ─────────────────────────────────────────────────────────────

const FALLBACK_LABEL: readonly LabelSourceStep[] = [
  { kind: "frontmatter_field", field: "title" },
  { kind: "first_heading" },
  { kind: "filename_stem" },
]

export const DEFAULT_NODE_TYPE_RULES: readonly NodeTypeRule[] = [
  {
    name: "requirement",
    path_pattern: "^docs/requirements/(REQ-\\d+)\\.md$",
    id_template: "requirement:{match1}",
    label_source: FALLBACK_LABEL,
    extraction_rule: "frontmatter",
  },
  {
    name: "decision",
    path_pattern: "^docs/decisions/(?:retired/)?(DEC-\\d+)\\.md$",
    id_template: "decision:{match1}",
    label_source: FALLBACK_LABEL,
    extraction_rule: "frontmatter",
  },
  {
    name: "specification",
    path_pattern: "^docs/specs/<(?!.*README\\>.md$).+\\.md$",
    id_template: "specification:{path}",
    label_source: [
      { kind: "frontmatter_field", field: "title" },
      { kind: "first_heading" },
      { kind: "path" },
    ],
    extraction_rule: "frontmatter",
  },
]

export const DEFAULT_RELATION_TYPE_RULES: readonly RelationTypeRule[] = [
  {
    name: "references",
    fields: ["canonical_owner", "context.paths"],
    reverse_direction: false,
  },
  {
    name: "supersedes",
    fields: ["superseded_by"],
    reverse_direction: true,
  },
  // defined_in, contains, extends are in the vocabulary but have no field-based
  // extraction. They are generated by containment/extension logic when the
  // relevant node types exist via augmentation.
]

export function defaultConfig(): ResolvedConfig {
  return {
    node_type_rules: DEFAULT_NODE_TYPE_RULES,
    node_type_vocabulary: [...DEFAULT_NODE_TYPE_VOCABULARY].sort(),
    relation_type_rules: DEFAULT_RELATION_TYPE_RULES,
    relation_type_vocabulary: [...DEFAULT_RELATION_TYPE_VOCABULARY].sort(),
    indexed_paths: [...DEFAULT_INDEXED_PATHS],
    discovery_roots: [],
    excluded_paths: [...EXCLUDED_PATHS],
  }
}

// ─── Augmentation loading ──────────────────────────────────────────────────────

export type AugmentationFile = {
  readonly node_types?: readonly {
    readonly name: string
    readonly path_pattern: string
    readonly id_template?: string
    readonly label_source?: readonly LabelSourceStep[]
    readonly extraction_rule?: ExtractionRule
  }[]
  readonly relation_types?: readonly {
    readonly name: string
    readonly fields?: readonly string[]
    readonly reverse_direction?: boolean
  }[]
  readonly indexed_paths?: readonly string[]
  readonly discovery_roots?: readonly string[]
}

export const AUGMENTATION_DEFAULT_PATH = ".agentdev/artifact-graph.yaml"

function parseLabelSource(
  raw: unknown,
  fallback: readonly LabelSourceStep[],
): readonly LabelSourceStep[] {
  if (!Array.isArray(raw) || raw.length === 0) return fallback
  return raw.map((step) => {
    if (typeof step !== "object" || step === null || !("kind" in step)) {
      throw new TypeError(`label_source step must have kind: ${JSON.stringify(step)}`)
    }
    const s = step as Record<string, unknown>
    switch (s["kind"]) {
      case "frontmatter_field":
        return { kind: "frontmatter_field", field: String(s["field"] ?? "") }
      case "first_heading":
        return { kind: "first_heading" }
      case "filename_stem":
        return { kind: "filename_stem" }
      case "path_group":
        return { kind: "path_group", group: Number(s["group"] ?? 1) }
      case "literal":
        return { kind: "literal", value: String(s["value"] ?? "") }
      case "path":
        return { kind: "path" }
      default:
        throw new TypeError(`unknown label_source kind: ${String(s["kind"])}`)
    }
  })
}

export function resolveConfig(augmentation: AugmentationFile | undefined): ResolvedConfig {
  const base = defaultConfig()
  if (augmentation === undefined) return base

  const baseNodeRules: NodeTypeRule[] = [...base.node_type_rules]
  const nodeVocab = new Set(base.node_type_vocabulary)
  const augmentedNodeRules: NodeTypeRule[] = []
  for (const raw of augmentation.node_types ?? []) {
    if (raw.name === undefined || raw.name.length === 0) {
      throw new TypeError("augmentation node_type requires name")
    }
    nodeVocab.add(raw.name)
    const existing = baseNodeRules.find((r) => r.name === raw.name)
    if (existing === undefined) {
      augmentedNodeRules.push({
        name: raw.name,
        path_pattern: raw.path_pattern,
        id_template: raw.id_template ?? `${raw.name}:{path}`,
        label_source: parseLabelSource(raw.label_source, [{ kind: "first_heading" }]),
        extraction_rule: raw.extraction_rule ?? "frontmatter",
      })
    } else if (raw.path_pattern !== existing.path_pattern) {
      const idx = baseNodeRules.indexOf(existing)
      baseNodeRules[idx] = {
        name: raw.name,
        path_pattern: raw.path_pattern,
        id_template: raw.id_template ?? existing.id_template,
        label_source: parseLabelSource(raw.label_source, existing.label_source),
        extraction_rule: raw.extraction_rule ?? existing.extraction_rule,
      }
    }
  }
  // Augmentation rules take priority over defaults: more specific project patterns
  // are tried before general standard patterns (e.g., integrity_rule before specification).
  const nodeRules = [...augmentedNodeRules, ...baseNodeRules]

  const relRules: RelationTypeRule[] = [...base.relation_type_rules]
  const relVocab = new Set(base.relation_type_vocabulary)
  for (const raw of augmentation.relation_types ?? []) {
    if (raw.name === undefined || raw.name.length === 0) {
      throw new TypeError("augmentation relation_type requires name")
    }
    relVocab.add(raw.name)
    const existing = relRules.find((r) => r.name === raw.name)
    const fields = raw.fields !== undefined ? [...raw.fields] : existing?.fields ?? []
    const reverse = raw.reverse_direction ?? existing?.reverse_direction ?? false
    if (existing === undefined) {
      relRules.push({ name: raw.name, fields, reverse_direction: reverse })
    } else {
      const idx = relRules.indexOf(existing)
      relRules[idx] = { name: raw.name, fields, reverse_direction: reverse }
    }
  }

  const indexedPaths = mergeUnique(base.indexed_paths, augmentation.indexed_paths ?? [])
  const discoveryRoots = mergeUnique(base.discovery_roots, augmentation.discovery_roots ?? [])

  return {
    node_type_rules: nodeRules,
    node_type_vocabulary: [...nodeVocab].sort(),
    relation_type_rules: relRules,
    relation_type_vocabulary: [...relVocab].sort(),
    indexed_paths: indexedPaths,
    discovery_roots: discoveryRoots,
    excluded_paths: base.excluded_paths,
  }
}

function mergeUnique(base: readonly string[], additions: readonly string[]): readonly string[] {
  const seen = new Set(base)
  for (const p of additions) seen.add(p)
  return [...seen]
}

export async function loadAugmentation(root: string, explicitPath?: string): Promise<AugmentationFile | undefined> {
  const path = explicitPath ?? AUGMENTATION_DEFAULT_PATH
  const fullPath = join(root, path)
  const file = Bun.file(fullPath)
  if (!(await file.exists())) return undefined
  const text = await file.text()
  return parseYaml(text)
}

function parseYaml(text: string): AugmentationFile {
  // Use Bun's YAML parser if available, otherwise simple fallback
  return Bun.YAML.parse(text) as AugmentationFile
}

export function validNodeTypes(config: ResolvedConfig): ReadonlySet<string> {
  return new Set(config.node_type_vocabulary)
}

export function validRelationTypes(config: ResolvedConfig): ReadonlySet<string> {
  return new Set(config.relation_type_vocabulary)
}
