// Behavioral distribution tests for the agentdev-textlint-guard plugin
// package (REQ-053-033 offline distribution + REQ-052-007 plugin projection).
//
// Covers the TS-009 distribution contract for the new plugin:
//   - consumer install (git-clone style and source-ZIP style checkouts)
//     projects plugins/agentdev-textlint-guard with a depth-1 loader shim,
//     and the vendored engine bundle travels with the projection
//   - archive install (scripts/consumer/archive/install.ps1 copy mode)
//     places the plugin as real files with the generated shim
//   - the final gate runs from every projection WITHOUT node_modules and
//     without network package fetching (dependencies are pre-resolved and
//     shipped as vendor/textlint-engine.bundle.json)
//   - install/self-sync generic enumeration covers the new plugin with no
//     special-case branching and no repo-local exclusion entry

// ADF-COVERS(verification): REQ-053-025, REQ-053-033, REQ-053-034
// ADF-COVERS(verification): REQ-052-006, REQ-052-007
// ADF-COVERS(verification): REQ-050-002, REQ-050-004

import { describe, expect, test } from "bun:test";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync, spawnSync } from "child_process";

const REPO_ROOT = path.resolve(import.meta.dir, "..", "..", "..");
const INSTALL_PS1 = path.join(REPO_ROOT, "scripts", "install.ps1");
const ARCHIVE_INSTALL_PS1 = path.join(REPO_ROOT, "scripts", "consumer", "archive", "install.ps1");
const SELF_SYNC_PS1 = path.join(REPO_ROOT, "scripts", "self-sync.ps1");
const PLUGIN_SOURCE_DIR = path.join(REPO_ROOT, "src", "opencode", "plugins", "agentdev-textlint-guard");

const CLEAN_DOC = "# 見出し\n\nこれは正常な文章である。\n";
const VIOLATING_DOC = "# 見出し\n\n半角カナ\uFF71\uFF72\uFF73が混入している。\n";

function rmrf(p: string): void {
  try {
    fs.rmSync(p, { recursive: true, force: true });
  } catch {
    /* swallow */
  }
}

function copyTree(src: string, dst: string, skip: (rel: string) => boolean = () => false): void {
  fs.mkdirSync(dst, { recursive: true });
  for (const ent of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, ent.name);
    const d = path.join(dst, ent.name);
    if (ent.isDirectory()) {
      if (ent.name === "node_modules") continue;
      copyTree(s, d, skip);
    } else if (ent.isFile()) {
      const rel = path.relative(src, s);
      if (skip(rel)) continue;
      fs.copyFileSync(s, d);
    }
  }
}

/** 実 plugin package を node_modules なしでフィクスチャへ配置する（オフライン導入の前提）。 */
function placeRealPlugin(parentSrcOpencode: string): void {
  copyTree(PLUGIN_SOURCE_DIR, path.join(parentSrcOpencode, "plugins", "agentdev-textlint-guard"), (rel) => {
    // テスト実行成果物は配布物に含めない
    return rel.replaceAll("\\", "/").startsWith("tests/");
  });
}

interface GateRun {
  readonly exitCode: number;
  readonly stdout: string;
}

function runGateFrom(projectionPluginDir: string, projectRoot: string): GateRun {
  const emptyCache = fs.mkdtempSync(path.join(os.tmpdir(), "adf-empty-cache-"));
  try {
    const r = spawnSync("bun", ["run", path.join(projectionPluginDir, "gate.ts"), "--root", projectRoot], {
      encoding: "utf8",
      env: { ...process.env, BUN_INSTALL_CACHE_DIR: emptyCache, BUN_INSTALL_BIN_DIR: emptyCache },
      maxBuffer: 16 * 1024 * 1024,
    });
    return { exitCode: r.status ?? -1, stdout: `${r.stdout ?? ""}${r.stderr ?? ""}` };
  } finally {
    rmrf(emptyCache);
  }
}

function runPwsh(file: string, args: readonly string[], cwd: string): { exitCode: number; stdout: string } {
  const r = spawnSync("pwsh", ["-NoProfile", "-NonInteractive", "-File", file, ...args], {
    cwd,
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  return { exitCode: r.status ?? -1, stdout: `${r.stdout ?? ""}${r.stderr ?? ""}` };
}

function writeDocs(root: string, files: Record<string, string>): void {
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(root, ...rel.split("/"));
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, "utf8");
  }
}

function assertNoNodeModules(root: string): void {
  expect(fs.existsSync(path.join(root, "node_modules"))).toBe(false);
  const pluginDir = path.join(root, ".opencode", "plugins", "agentdev-textlint-guard");
  expect(fs.existsSync(path.join(pluginDir, "node_modules"))).toBe(false);
}

function expectShim(pluginsDir: string): void {
  const shim = path.join(pluginsDir, "agentdev-textlint-guard.ts");
  expect(fs.existsSync(shim)).toBe(true);
  expect(fs.readFileSync(shim, "utf8")).toBe(
    `// Generated by scripts/install.ps1 / scripts/self-sync.ps1 - do not edit.\n` +
      `export { default } from "./agentdev-textlint-guard/plugin.ts";\n`,
  );
}

describe("agentdev-textlint-guard distribution / consumer install (TS-009)", () => {
  function consumerScenario(label: string, gitCloneStyle: boolean): void {
    test(`${label}: junction + shim + vendored bundle + offline final gate`, () => {
      const root = fs.mkdtempSync(path.join(os.tmpdir(), `adftl-dist-${gitCloneStyle ? "git" : "zip"}-`));
      try {
        const srcOpencode = path.join(root, ".agentdev-plugin", "src", "opencode");
        fs.mkdirSync(path.join(srcOpencode, "commands", "agentdev"), { recursive: true });
        fs.writeFileSync(path.join(srcOpencode, "commands", "agentdev", "case-run.md"), "# case-run\n", "utf8");
        // check モードは .opencode/tools の存在を期待するため既存テストと同じ最小 tools エントリを置く
        fs.mkdirSync(path.join(srcOpencode, "tools", "agentdev-gh"), { recursive: true });
        fs.writeFileSync(path.join(srcOpencode, "tools", "agentdev-gh", "index.ts"), "// tool\n", "utf8");
        placeRealPlugin(srcOpencode);
        fs.mkdirSync(path.join(root, "scripts", "consumer"), { recursive: true });
        fs.copyFileSync(INSTALL_PS1, path.join(root, "scripts", "install.ps1"));
        fs.copyFileSync(path.join(REPO_ROOT, "scripts", "consumer", "common.ps1"), path.join(root, "scripts", "consumer", "common.ps1"));
        execFileSync("git", ["init", "-q", "-b", "main"], { cwd: root });
        execFileSync("git", ["config", "user.email", "t@t"], { cwd: root });
        execFileSync("git", ["config", "user.name", "t"], { cwd: root });
        if (gitCloneStyle) {
          const plugin = path.join(root, ".agentdev-plugin");
          execFileSync("git", ["init", "-q", "-b", "main"], { cwd: plugin });
          execFileSync("git", ["config", "user.email", "t@t"], { cwd: plugin });
          execFileSync("git", ["config", "user.name", "t"], { cwd: plugin });
          execFileSync("git", ["add", "-A"], { cwd: plugin });
          execFileSync("git", ["commit", "-q", "-m", "plugin"], { cwd: plugin });
        }

        const apply = runPwsh(path.join(root, "scripts", "install.ps1"), ["-Mode", "apply"], root);
        expect(apply.exitCode).toBe(0);

        const pluginsDir = path.join(root, ".opencode", "plugins");
        const pluginLink = path.join(pluginsDir, "agentdev-textlint-guard");
        expect(fs.existsSync(path.join(pluginLink, "plugin.ts"))).toBe(true);
        expect(fs.existsSync(path.join(pluginLink, "vendor", "textlint-engine.bundle.json"))).toBe(true);
        expect(fs.existsSync(path.join(pluginLink, "rules", "default-prh.yml"))).toBe(true);
        expectShim(pluginsDir);

        const check = runPwsh(path.join(root, "scripts", "install.ps1"), ["-Mode", "check"], root);
        expect(check.exitCode).toBe(0);

        // オフライン最終検査（node_modules なし・空キャッシュ環境変数）
        assertNoNodeModules(root);
        writeDocs(root, { "docs/ok.md": CLEAN_DOC });
        const pass = runGateFrom(pluginLink, root);
        expect(pass.exitCode).toBe(0);
        expect(pass.stdout).toContain("PASS");

        writeDocs(root, { "docs/bypass.md": VIOLATING_DOC });
        const fail = runGateFrom(pluginLink, root);
        expect(fail.exitCode).toBe(1);
        expect(fail.stdout).toContain("no-hankaku-kana");
      } finally {
        rmrf(root);
      }
    }, 300000);
  }

  consumerScenario("git clone checkout", true);
  consumerScenario("source ZIP checkout (.git absent inside the plugin checkout)", false);
});

describe("agentdev-textlint-guard distribution / archive install (TS-009)", () => {
  test("archive installer places plugin files + generated shim and the gate runs offline", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "adftl-arc-"));
    try {
      const stageSrc = path.join(root, "archive", "src", "opencode");
      fs.mkdirSync(path.join(stageSrc, "commands", "agentdev"), { recursive: true });
      fs.writeFileSync(path.join(stageSrc, "commands", "agentdev", "case-run.md"), "# case-run\n", "utf8");
      fs.mkdirSync(path.join(stageSrc, "skills", "agentdev-workflow-case-run"), { recursive: true });
      fs.writeFileSync(path.join(stageSrc, "skills", "agentdev-workflow-case-run", "SKILL.md"), "# case-run\n", "utf8");
      placeRealPlugin(stageSrc);

      const target = path.join(root, "consumer", ".opencode");
      const r = runPwsh(ARCHIVE_INSTALL_PS1, ["-Source", path.join(root, "archive", "src", "opencode"), "-Target", target, "-Mode", "copy"], root);
      expect(r.exitCode).toBe(0);

      const pluginsDir = path.join(target, "plugins");
      const pluginDir = path.join(pluginsDir, "agentdev-textlint-guard");
      expect(fs.existsSync(path.join(pluginDir, "plugin.ts"))).toBe(true);
      expect(fs.existsSync(path.join(pluginDir, "gate.ts"))).toBe(true);
      expect(fs.existsSync(path.join(pluginDir, "vendor", "textlint-engine.bundle.json"))).toBe(true);
      expectShim(pluginsDir);

      // archive 導入は実ファイル配置（junction-free）
      const stat = fs.lstatSync(pluginDir);
      expect(stat.isSymbolicLink()).toBe(false);

      const consumerRoot = path.join(root, "consumer");
      assertNoNodeModules(consumerRoot);
      writeDocs(consumerRoot, { "docs/ok.md": CLEAN_DOC, "docs/violating.md": VIOLATING_DOC });
      const gate = runGateFrom(pluginDir, consumerRoot);
      expect(gate.exitCode).toBe(1);
      expect(gate.stdout).toContain("violating.md");
      expect(gate.stdout).toContain("no-hankaku-kana");
    } finally {
      rmrf(root);
    }
  }, 300000);
});

describe("agentdev-textlint-guard distribution / generic enumeration contract (TS-009)", () => {
  test("install.ps1 and package-release-archive.ps1 keep the plugin out of repo-local exclusions", () => {
    const install = fs.readFileSync(INSTALL_PS1, "utf8");
    const release = fs.readFileSync(
      path.join(REPO_ROOT, "scripts", "self", "release", "package-release-archive.ps1"),
      "utf8",
    );
    const archiveInstall = fs.readFileSync(ARCHIVE_INSTALL_PS1, "utf8");
    for (const [name, text] of [
      ["install.ps1", install],
      ["package-release-archive.ps1", release],
      ["archive install.ps1", archiveInstall],
    ] as const) {
      // repo-local 除外リストは agentdev-distribution-boundary-guard のみ（追加禁止）
      const repoLocalMatch = text.match(/\$repoLocalPluginNames?\s*=\s*@\(([^)]*)\)/i);
      expect(repoLocalMatch).not.toBeNull();
      if (repoLocalMatch !== null) {
        expect(repoLocalMatch[1]).not.toContain("agentdev-textlint-guard");
      }
      // 汎用列挙（agentdev-* フィルタ）が存在する
      expect(text).toMatch(/agentdev-\*/);
      void name;
    }
  });

  test("self-sync.ps1 enumerates plugins generically and does not exclude the plugin", () => {
    const sync = fs.readFileSync(SELF_SYNC_PS1, "utf8");
    expect(sync).toMatch(/plugins/);
    expect(sync).toMatch(/agentdev-\*/);
    expect(sync).not.toContain("agentdev-textlint-guard");
  });

  test("release archive packaging copies plugin files including the vendored bundle (node_modules stripped)", () => {
    const release = fs.readFileSync(
      path.join(REPO_ROOT, "scripts", "self", "release", "package-release-archive.ps1"),
      "utf8",
    );
    // Copy-Item -Recurse で plugin package 全体を stage へコピーし、
    // node_modules だけが除去される（vendor/ は残る）
    expect(release).toMatch(/Filter "node_modules"/);
    const vendorRel = "vendor/textlint-engine.bundle.json";
    expect(fs.existsSync(path.join(PLUGIN_SOURCE_DIR, ...vendorRel.split("/")))).toBe(true);
  });
});
