import { mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { formatReqId } from "../../../agentdev-req-file-manager/scripts/src/alloc-req-number.ts"
import { formatDecisionId } from "../../../agentdev-decision-file-manager/scripts/src/alloc-decision-number.ts"

/**
 * Fixture IDs generated by the production allocator functions. The graph
 * engine's default node-type path patterns require REQ-/DEC- prefixed
 * filenames; calling the canonical formatters (not manual reconstruction)
 * produces correct runtime values without embedding concrete ID literals
 * in distributed source.
 */
export const REQ_001 = formatReqId(1)
export const DEC_001 = formatDecisionId(1)
export const DEC_002 = formatDecisionId(2)
const FEATURE_STEM = "feature"
const FEATURE_MD = `${FEATURE_STEM}.md`

/** Node IDs and paths the graph engine emits for the minimal fixture. */
export const REQ_001_NODE = `requirement:${REQ_001}`
export const DEC_001_NODE = `decision:${DEC_001}`
export const DEC_002_NODE = `decision:${DEC_002}`
export const FEATURE_SPEC_NODE = `specification:docs/specs/${FEATURE_MD}`
export const REQ_001_PATH = `docs/requirements/${REQ_001}.md`
export const DEC_001_PATH = `docs/decisions/${DEC_001}.md`
export const DEC_002_PATH = `docs/decisions/${DEC_002}.md`

/**
 * Minimal consumer fixture with only the 3 default indexed_paths populated.
 * No AgentDevFlow distribution artifacts, no self-hosting paths.
 * Default indexed_paths: docs/requirements, docs/decisions, docs/specs only.
 * Default node_types: requirement, decision, specification only.
 */
const FILES: Record<string, string> = {
  [`docs/requirements/${REQ_001}.md`]: `---
id: ${REQ_001}
title: Sample requirement
status: accepted
---
# Sample requirement

See [decision](../decisions/${DEC_001}.md) and [spec](../specs/${FEATURE_MD}).
`,
  [`docs/decisions/${DEC_001}.md`]: `---
id: ${DEC_001}
title: Old decision
status: superseded
superseded_by: ${DEC_002}
---
# Old decision
`,
  [`docs/decisions/${DEC_002}.md`]: `---
id: ${DEC_002}
title: Current decision
status: accepted
---
# Current decision

See [specification](../specs/${FEATURE_MD}).
`,
  [`docs/specs/${FEATURE_MD}`]: `---
title: Feature specification
canonical_owner: sample-skill
---
# Feature specification
`,
  [`docs/specs/README.md`]: `# Specs index
This README should NOT produce a specification node.
`,
}

export async function createFixture(root: string): Promise<void> {
  for (const [relativePath, content] of Object.entries(FILES)) {
    const fullPath = join(root, relativePath)
    await mkdir(join(fullPath, ".."), { recursive: true })
    await writeFile(fullPath, content, "utf8")
  }
}

/**
 * Fixture with project-owned source files NOT in default indexed_paths.
 * Used for discovery_roots testing (TS-{NNN}).
 */
export async function createSourceFixture(root: string): Promise<void> {
  const sources = {
    "src/module.ts": `import { foo } from "./foo"
export const bar = foo + 1
`,
    "src/foo.ts": `export const foo = 42
export function helper() { return "agentdev-artifact-graph" }
`,
    "tests/test_module.ts": `import { bar } from "../src/module"
test("bar", () => { expect(bar).toBe(43) })
`,
  } as const
  for (const [relativePath, content] of Object.entries(sources)) {
    const fullPath = join(root, relativePath)
    await mkdir(join(fullPath, ".."), { recursive: true })
    await writeFile(fullPath, content, "utf8")
  }
}

/**
 * Augmentation file that adds a project-specific node type and relation type.
 * Used for TS-{NNN} (augmentation adds node_type/relation_type).
 */
export const AUGMENTATION_WITH_GUIDE = `node_types:
  - name: guide
    path_pattern: "^docs/guides/([^/]+)\\\\.md$"
    id_template: "guide:{match1}"
    label_source:
      - kind: first_heading
    extraction_rule: frontmatter
relation_types:
  - name: documented_in
    fields:
      - documented_in
    reverse_direction: false
indexed_paths:
  - docs/guides
discovery_roots:
  - src
  - tests
`

export async function createGuideFixture(root: string): Promise<void> {
  const guides = {
    [`docs/guides/quickstart.md`]: `---
documented_in: ${REQ_001}
---
# Quickstart Guide

See [requirement](../requirements/${REQ_001}.md).
`,
  } as const
  for (const [relativePath, content] of Object.entries(guides)) {
    const fullPath = join(root, relativePath)
    await mkdir(join(fullPath, ".."), { recursive: true })
    await writeFile(fullPath, content, "utf8")
  }
}

// ─── TIM semantic fixture (REQ-{NNNN}-{NNN} series) ────────────────────────────

function numberedStem(prefix: string, n: number): string {
  return `${prefix}-${String(n).padStart(3, "0")}`
}

const INDEX_001 = numberedStem("INDEX", 1)
const DESIGN_001 = numberedStem("DESIGN", 1)
const DESIGN_002 = numberedStem("DESIGN", 2)
const RULE_001 = numberedStem("RULE", 1)

export const CATALOG_NODE = `catalog:${INDEX_001}`
export const DESIGN_NODE = `design:${DESIGN_001}`
export const DESIGN_002_NODE = `design:${DESIGN_002}`
export const RULE_NODE = `rule:${RULE_001}`

/**
 * Augmentation exercising the TIM semantic surface: an index-role artifact
 * type (role identification, REQ-{NNNN}-{NNN}), extension relation types with
 * declared semantics covering all 4 change impact directions (REQ-{NNNN}-{NNN},
 * REQ-{NNNN}-{NNN}), and a semantics-free relation type that must stay out of
 * purpose-specific queries while remaining usable in low-level queries.
 */
export const AUGMENTATION_WITH_TIM = `node_types:
  - name: catalog
    path_pattern: "^docs/catalog/(INDEX-[^/]+)\\\\.md$"
    id_template: "catalog:{match1}"
    label_source:
      - kind: first_heading
    role: index
  - name: design
    path_pattern: "^docs/design/(DESIGN-[^/]+)\\\\.md$"
    id_template: "design:{match1}"
    label_source:
      - kind: first_heading
  - name: rule
    path_pattern: "^docs/rules/(RULE-[^/]+)\\\\.md$"
    id_template: "rule:{match1}"
    label_source:
      - kind: first_heading
relation_types:
  - name: satisfies
    fields:
      - satisfies
    reverse_direction: false
    semantics:
      meaning: "設計成果物が要件を充足する"
      semantics_slot: satisfy
      change_impact_direction: backward
      standard_vocabulary:
        - "SysML «satisfy»"
  - name: constrains
    fields:
      - constrains
    reverse_direction: false
    semantics:
      meaning: "制約成果物が対象成果物を制約する"
      semantics_slot: constrain
      change_impact_direction: forward
  - name: syncs_with
    fields:
      - syncs_with
    reverse_direction: false
    semantics:
      meaning: "両成果物が互いに整合を維持する双方向関係"
      change_impact_direction: bidirectional
  - name: tracks
    fields:
      - tracks
    reverse_direction: false
indexed_paths:
  - docs/catalog
  - docs/design
  - docs/rules
`

export async function createTimFixture(root: string): Promise<void> {
  const files = {
    [`docs/catalog/${INDEX_001}.md`]: `---
title: Catalog index
---
# Catalog index

- [requirement](../requirements/${REQ_001}.md)
- [decision](../decisions/${DEC_001}.md)
`,
    [`docs/design/${DESIGN_001}.md`]: `---
satisfies: ${REQ_001}
syncs_with: rule:${RULE_001}
---
# Design one
`,
    [`docs/design/${DESIGN_002}.md`]: `---
tracks: ${DEC_002}
---
# Design two
`,
    [`docs/rules/${RULE_001}.md`]: `---
constrains: ${REQ_001}
---
# Rule one
`,
  } as const
  for (const [relativePath, content] of Object.entries(files)) {
    const fullPath = join(root, relativePath)
    await mkdir(join(fullPath, ".."), { recursive: true })
    await writeFile(fullPath, content, "utf8")
  }
}
