import { mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { formatReqId } from "../../../agentdev-req-file-manager/scripts/src/alloc-req-number.ts"
import { formatDecisionId } from "../../../agentdev-decision-file-manager/scripts/src/alloc-decision-number.ts"

/**
 * Trace query fixture IDs generated by the canonical allocators (see fixture.ts).
 * The fixture exercises: general references, supersedes, realization series via
 * augmentation, an index-role hub, a semantics-undefined relation, an isolated
 * requirement, a constraint violation, and a directed reference cycle.
 */
export const T_REQ1 = formatReqId(1)
export const T_REQ2 = formatReqId(2)
export const T_REQ3 = formatReqId(3)
export const T_REQ4 = formatReqId(4)
export const T_REQ5 = formatReqId(5)
export const T_REQ9 = formatReqId(9)
export const T_DEC1 = formatDecisionId(1)
export const T_DEC2 = formatDecisionId(2)

const FEATURE_STEM = "feature"
const FEATURE_MD = `${FEATURE_STEM}.md`
export const NOWHERE_MD = "nowhere.md"

export const SPEC_PATH = `docs/specs/${FEATURE_MD}`
export const SRC_PATH = `src/${FEATURE_STEM}.ts`

export const REQ1_NODE = `requirement:${T_REQ1}`
export const REQ2_NODE = `requirement:${T_REQ2}`
export const REQ3_NODE = `requirement:${T_REQ3}`
export const REQ4_NODE = `requirement:${T_REQ4}`
export const REQ5_NODE = `requirement:${T_REQ5}`
export const DEC1_NODE = `decision:${T_DEC1}`
export const DEC2_NODE = `decision:${T_DEC2}`
export const SPEC_NODE = `specification:${SPEC_PATH}`
export const HUB_NODE = "index_doc:hub.md"
export const SRC_NODE = `source_code:${FEATURE_STEM}.ts`

export function traceAugmentationYaml(options: {
  readonly indexRole: boolean
  readonly relatedLimit?: number
}): string {
  const lines = [
    "node_types:",
    "  - name: source_code",
    '    path_pattern: "^src/([^/]+\\\\.ts)$"',
    '    id_template: "source_code:{match1}"',
    "    label_source:",
    "      - kind: path",
    "    extraction_rule: filesystem",
    "  - name: index_doc",
    '    path_pattern: "^docs/index/([^/]+\\\\.md)$"',
    '    id_template: "index_doc:{match1}"',
    "    label_source:",
    "      - kind: first_heading",
    "    extraction_rule: frontmatter",
  ]
  if (options.indexRole) lines.push("    role: index")
  lines.push(
    "relation_types:",
    "  - name: implemented_by",
    "    fields:",
    "      - implemented_by",
    "    reverse_direction: false",
    "    semantics:",
    '      meaning: "成果物が当該ソースコードによって実装される"',
    "      semantics_slot: implement",
    "      change_impact_direction: forward",
    "      standard_vocabulary: []",
    "  - name: mentioned_in",
    "    fields:",
    "      - mentioned_in",
    "    reverse_direction: false",
    "indexed_paths:",
    "  - src",
    "  - docs/index",
    "discovery_roots:",
    "  - src",
    "query_settings:",
    "  concentration_threshold: 3",
  )
  if (options.relatedLimit !== undefined) {
    lines.push("  limits:", `    related: ${options.relatedLimit}`)
  }
  lines.push(
    "relation_constraints:",
    "  - relation_type: implemented_by",
    "    allowed_source_types:",
    "      - specification",
    "    allowed_target_types:",
    "      - source_code",
  )
  return `${lines.join("\n")}\n`
}

const FILES: Record<string, string> = {
  [`docs/requirements/${T_REQ1}.md`]: `---
id: ${T_REQ1}
title: Representative requirement
status: accepted
---
# Representative requirement

See [decision](../decisions/${T_DEC1}.md) and [spec](../specs/${FEATURE_MD}).
`,
  [`docs/requirements/${T_REQ2}.md`]: `---
id: ${T_REQ2}
title: Isolated requirement
status: accepted
---
# Isolated requirement
`,
  [`docs/requirements/${T_REQ3}.md`]: `---
id: ${T_REQ3}
title: Cycle participant
status: accepted
---
# Cycle participant

See [decision2](../decisions/${T_DEC2}.md).
`,
  [`docs/requirements/${T_REQ4}.md`]: `---
id: ${T_REQ4}
title: Miswired requirement
status: accepted
implemented_by: ${SRC_PATH}
---
# Miswired requirement
`,
  [`docs/requirements/${T_REQ5}.md`]: `---
id: ${T_REQ5}
title: Unlinked semantics probe
status: accepted
mentioned_in: ${T_DEC2}
---
# Unlinked semantics probe
`,
  [`docs/decisions/${T_DEC1}.md`]: `---
id: ${T_DEC1}
title: Old decision
status: superseded
superseded_by: ${T_DEC2}
---
# Old decision
`,
  [`docs/decisions/${T_DEC2}.md`]: `---
id: ${T_DEC2}
title: Current decision
status: accepted
---
# Current decision

See [specification](../specs/${FEATURE_MD}).
`,
  [SPEC_PATH]: `---
title: Feature specification
implemented_by: ${SRC_PATH}
---
# Feature specification

See [req3](../requirements/${T_REQ3}.md).
`,
  ["docs/index/hub.md"]: `# Index hub

- [req1](../requirements/${T_REQ1}.md)
- [dec1](../decisions/${T_DEC1}.md)
- [dec2](../decisions/${T_DEC2}.md)
- [spec](../specs/${FEATURE_MD})
`,
  [SRC_PATH]: `export const feature = 1
`,
}

export async function createTraceFixture(root: string, augmentation: string): Promise<void> {
  for (const [relativePath, content] of Object.entries({ ...FILES, ".agentdev/artifact-graph.yaml": augmentation })) {
    const fullPath = join(root, relativePath)
    await mkdir(join(fullPath, ".."), { recursive: true })
    await writeFile(fullPath, content, "utf8")
  }
}
